#!/bin/bash
export TMPDIR=/home/drodri/apps/juegos-backend/tmp
mkdir -p /home/drodri/apps/juegos-backend/tmp
PIDFILE="/home/drodri/apps/juegos-backend/tmp/node.pid"
#NODE=/home/drodri/apps/juegos-backend/node/bin/node
NODE=/home/drodri/apps/juegos/node/bin/node

if [ -e "$PIDFILE" ] && (pgrep -u drodri | grep -x -f $PIDFILE &> /dev/null); then
  echo "Node.js for juegos-backend already running."
  exit 99
fi

cd /home/drodri/apps/juegos-backend
/usr/sbin/daemonize -c /home/drodri/apps/juegos-backend -a -e ~/logs/apps/juegos-backend/node_error.log -o ~/logs/apps/juegos-backend/node_output.log -p $PIDFILE $NODE server.js

echo "Started Node.js for juegos-backend."
